import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Sparkles, Download, TrendingUp, AlertTriangle, Target } from "lucide-react";
import { Badge } from "@/components/ui/badge";

export const ExecutiveBrief = () => {
  return (
    <Card className="card-elegant animate-in">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" />
            <CardTitle className="text-xl">AI Executive Brief</CardTitle>
          </div>
          <Button variant="outline" size="sm" className="gap-2">
            <Download className="h-4 w-4" />
            Export
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Badge variant="outline" className="bg-primary/10 text-primary border-primary/20">
              Week of Nov 25, 2025
            </Badge>
          </div>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Portfolio health remains <span className="font-semibold text-success">strong</span> with 78% launch success
            rate. Revenue performance is <span className="font-semibold text-primary">+18.2% QoQ</span>, driven by
            Digital Wallet API and Cross-Border Pay commercialization.
          </p>
        </div>

        <div className="space-y-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <TrendingUp className="h-4 w-4 text-success" />
              <h4 className="font-semibold text-sm">Top Investment Candidates</h4>
            </div>
            <ul className="space-y-2 ml-6">
              <li className="text-sm">
                <span className="font-medium text-foreground">Cross-Border Pay:</span>
                <span className="text-muted-foreground"> 95% readiness, 96% success probability</span>
              </li>
              <li className="text-sm">
                <span className="font-medium text-foreground">Analytics Suite:</span>
                <span className="text-muted-foreground"> Strong adoption velocity, expand sales coverage</span>
              </li>
            </ul>
          </div>

          <div>
            <div className="flex items-center gap-2 mb-2">
              <AlertTriangle className="h-4 w-4 text-destructive" />
              <h4 className="font-semibold text-sm">Risk & Kill Recommendations</h4>
            </div>
            <ul className="space-y-2 ml-6">
              <li className="text-sm">
                <span className="font-medium text-destructive">Crypto Gateway:</span>
                <span className="text-muted-foreground">
                  {" "}
                  82 risk score, 55% readiness — recommend de-prioritization
                </span>
              </li>
              <li className="text-sm">
                <span className="font-medium text-warning">Loyalty Platform:</span>
                <span className="text-muted-foreground"> 68 risk, requires governance intervention</span>
              </li>
            </ul>
          </div>

          <div>
            <div className="flex items-center gap-2 mb-2">
              <Target className="h-4 w-4 text-primary" />
              <h4 className="font-semibold text-sm">Channel Conflicts Detected</h4>
            </div>
            <ul className="space-y-2 ml-6">
              <li className="text-sm text-muted-foreground">
                Smart Routing overlaps with Merchant Portal in Southeast sales territory
              </li>
            </ul>
          </div>
        </div>

        <div className="pt-4 border-t">
          <p className="text-xs text-muted-foreground italic">
            Generated by MSIP AI Intelligence Engine • Last updated 2 hours ago
          </p>
        </div>
      </CardContent>
    </Card>
  );
};
