// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback to hardcoded values for Lovable deployment
// These are public keys (anon key) - safe to expose
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://czcpjmqsvekaoqkxgrze.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6Y3BqbXFzdmVrYW9xa3hncnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxNTcxNjIsImV4cCI6MjA1MDczMzE2Mn0.DSQJ-VoE-wEKKg0hFJBGbcyGkJMJRPsxzGNl8mrPfn4';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});